export const CATEGORIES_GET_SUCCESS = 'CATEGORIES_GET_SUCCESS';
export const CATEGORIES_GET_FAILURE = 'CATEGORIES_GET_FAILURE';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';
export const GET_BANNERS_FAILURE = 'GET_BANNERS_FAILURE';

export const GET_SLIDER_SUCCESS = 'GET_SLIDER_SUCCESS';
export const GET_SLIDER_FAILURE = 'GET_SLIDER_FAILURE';

export const LOCATICONS_GET_SUCCESS = 'LOCATICONS_GET_SUCCESS';
export const LOCATICONS_GET_FAILURE = 'LOCATICONS_GET_FAILURE';

export const GET_CATALOGS_SUCCESS = 'GET_CATALOGS_SUCCESS';
export const GET_CATALOGS_FAILURE = 'GET_CATALOGS_FAILURE';

export const GET_LITRATURE_SUCCESS = 'GET_LITRATURE_SUCCESS';
export const GET_LITRATURE_FAILURE = 'GET_LITRATURE_FAILURE';

export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';

export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAILURE = 'GET_NEWS_FAILURE';

export const GET_NEWSBYID_SUCCESS = 'GET_NEWSBYID_SUCCESS';
export const GET_NEWSBYID_FAILURE = 'GET_NEWSBYID_FAILURE';

export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAILURE = 'GET_BRANDS_FAILURE';

export const GET_PRODUCT_ATTRIBUTES_SUCCESS = 'GET_PRODUCT_ATTRIBUTES_SUCCESS';
export const GET_PRODUCT_ATTRIBUTES_FAILURE = 'GET_PRODUCT_ATTRIBUTES_FAILURE';

export const GET_SALES_REPS_SUCCESS = 'GET_SALES_REPS_SUCCESS';
export const GET_SALES_REPS_FAILURE = 'GET_SALES_REPS_FAILURE';
